meta-api:
  data-directory: ${DATA_DIR:./data}
  minecraft-launcher-meta-url: https://piston-meta.mojang.com/mc/game/version_manifest_v2.json

  # Maven artifact version discovery
  components:
    - maven-repository-id: releases
      group-id: net.neoforged
      artifact-id: neoforge
      publication-rules:
          # No Gradle ".module" metadata in these versions
          - version-ranges:
              - '[20.2-alpha,20.3)'
              - '[20.3-alpha,20.4)'
              - '[20.4-alpha,20.4.238)'
              - '[20.5-alpha,20.6)'
              - '[20.6-alpha,20.6.122)'
            artifacts:
            - extension: pom
            - classifier: universal
            - classifier: installer
            - classifier: userdev
            - classifier: sources
            - classifier: changelog
              extension: txt
              optional: true
          - artifacts:
            - extension: pom
            - classifier: universal
            - classifier: installer
            - classifier: userdev
            - classifier: sources
            - extension: module
            - classifier: changelog
              extension: txt
              optional: true
    # - maven-repository-id: releases
    #   group-id: net.neoforged.fancymodloader
    #   artifact-id: loader

  maven-repositories:
    - id: releases
      #url: https://maven.prod.k8s.neoforged.net/releases/
      url: http://localhost:8088/

scheduled-tasks:
  maven-version-discovery:
    enabled: true
    cronPattern: "0 */10 * * * *"
  minecraft-version-discovery:
    enabled: true
    cronPattern: "0 */5 * * * *"

spring:
  application:
    name: meta-api

  datasource:
    url: jdbc:sqlite:${meta-api.data-directory}/meta-api.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,scheduledtasks
